---
# Configuring systemd and start Webapp.


- name: install on-webapp-demo systemd unit file
  template: src=on-webapp-demo.service.j2 dest=/etc/systemd/system/on-webapp-demo.service

- name: start on-webapp-demo
  systemd: state=started name=on-webapp-demo.service daemon_reload=yes enabled=yes
